pipeline {
    agent any

    tools {
        maven 'Maven3'
        jdk 'Java21'
    }

    stages {
        stage('Build') {
            steps {
                dir('OrangeHRM') {
                    bat 'mvn clean compile'
                }
            }
        }

        stage('Test') {
            steps {
                dir('OrangeHRM') {
                    bat 'mvn test'
                }
            }
        }

        stage('Report') {
            steps {
                publishHTML(target: [
                    reportDir: 'OrangeHRM/test-output',
                    reportFiles: 'emailable-report.html',
                    reportName: 'Automation Report',
                    keepAll: true,
                    alwaysLinkToLastBuild: true,
                    allowMissing: true
                ])
            }
        }
    }

    post {
        always {
            archiveArtifacts artifacts: 'OrangeHRM/ScreenShots/*.png', fingerprint: true, allowEmptyArchive: true
        }
        success {
            echo 'Build Passed'
        }
        failure {
            echo 'Build Failed'
        }
    }
}
